---
book_repo: cloudfoundry/docs-book-cloudfoundry
cred_repo: pivotal-cf/docs-oss-site-credentials

sections:
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
  directory: concepts
- repository:
    name: cloudfoundry/docs-dev-guide
  directory: devguide
- repository:
    name: cloudfoundry/docs-cf-admin
  directory: adminguide
- repository:
    name: cloudfoundry/docs-services
  directory: services
- repository:
    name: cloudfoundry/docs-deploying-cf
  directory: deploying
- repository:
    name: cloudfoundry/docs-bosh
  directory: bosh
- repository:
    name: cloudfoundry/docs-running-cf
  directory: running
- repository:
    name: cloudfoundry/docs-buildpacks
  directory: buildpacks

template_variables:
  app_domain: example.com
  quota_resource: quota space
  external_ips: external IP addresses
  admin: your Cloud Foundry administrator
  api_endpoint: <a href="http://docs.cloudfoundry.org/running/cf-api-endpoint.html">the URL of the Cloud Controller in your Cloud Foundry instance</a>
  console_2: If you have a Cloud Foundry account, refer to the <a href="http://docs.cloudfoundry.org/running/cf-api-endpoint.html">Indentifying the API Endpoint for your Cloud Foundry Instance</a> topic to determine the URL of the Cloud Controller in your Cloud Foundry instance. Click <strong>Manage Cloud...</strong> to add this URL to your Cloud Foundry account. Validate the account and continue through the wizard.</a>
  info_loc: In your Cloud Foundry deployment manifest
  uaa_cred: refer to the the <code>uaa scim</code> section
  GSG_intro_sentence:
  product_full: Cloud Foundry
  product_short: Cloud Foundry
  known_issues: <a href="http://docs.cloudfoundry.org/running/troubleshooting.html">Troubleshooting Cloud Foundry</a>
  dev_console_note:
  dev_console_1:
  dev_console_2: CLI
  dev_console_3:
  dev_console_4:
  dev_console_5:
  gen_GSG:
  cli_v6: <a href="http://docs.cloudfoundry.org/devguide/installcf/whats-new-v6.html">Getting Started with cf v6</a>

public_host: docs.cloudfoundry.org

